spring:
  application:
    name: doctour-be

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${DOC_DB_USERNAME}
    password: ${DOC_DB_PASSWORD}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-only
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: ${DOC_EMAIL_HOST}
    port: ${DOC_EMAIL_PORT}
    username: ${DOC_EMAIL_USERNAME}
    password: ${DOC_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${DOC_JWT_SECRET}
  expiration: 900000
  refresh-expiration: 2592000000

app:
  frontend-url: ${DOC_FRONTEND_URL}
  magic-link:
    expiry-hours: 24

logging:
  level:
    root: INFO
