spring:
  application:
    name: doctour-be

  datasource:
    driver-class-name: org.postgresql.Driver
    url: $DOC_DB_URL
    username: $DOC_DB_USERNAME
    password: $DOC_DB_PASSWORD

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  mail:
    host: $DOC_EMAIL_HOST
    port: $DOC_EMAIL_PORT
    username: $DOC_MAIL_USERNAME
    password: $DOC_EMAIL_PASSWORD
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: $DOC_JWT_SECRET
  expiration: 900000
  refresh-expiration: 2592000000

doctour:
  app:
    frontend-url: $DOC_FRONTEND_URL
